apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: mateapp
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    args:
    - sleep
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "100Mi"
