apiVersion: v1
kind: Service
metadata:
  name: todoapp-nodeport-service
  namespace: todoapp
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
