apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: mateapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: shcherbanvasyl499/todoapp:3.0.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /api/health/
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /api/ready/
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod-1
  namespace: mateapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: shcherbanvasyl499/todoapp:3.0.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /api/health/
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /api/ready/
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 5
